version: '2'
volumes:
  mantis-db:
services:
  mantisbt:
    build:
      context: ./
    container_name: mantisbt
    environment:
      - MANTIS_ENABLE_ADMIN=1
      - MANTIS_CONFIG_HOSTNAME='db'
      - MANTIS_CONFIG_DB_TYPE='mysqli'
      - MANTIS_CONFIG_DATABASE_NAME='mantis'
      - MANTIS_CONFIG_DB_USERNAME='root'
      - MANTIS_CONFIG_DB_PASSWORD='mantis'
      - MANTIS_CONFIG_CRYPTO_MASTER_SALT='+MIBUM6GgKXGeN7h5MPkb2GNW52CLObSQOvYZxVHjfmGYzKCcBLlGduJi/6aeCgRo5zCTT5XhEP2OdyVAXC9w=='
      - MANTIS_CONFIG_LOG_LEVEL=LOG_EMAIL|LOG_EMAIL_RECIPIENT
      - MANTIS_CONFIG_LOG_DESTINATION=''
      - MANTIS_CONFIG_SHOW_DETAILED_ERRORS=ON
      - MANTIS_CONFIG_DEFAULT_TIMEZONE='Europe/Paris'
      - MANTIS_CONFIG_PHPMAILER_METHOD=PHPMAILER_METHOD_SMTP
      - MANTIS_CONFIG_ADMINISTRATOR_EMAIL='<your email>'
      - MANTIS_CONFIG_WEBMASTER_EMAIL='<your email>'
      - MANTIS_CONFIG_RETURN_PATH_EMAIL='<your email>'
      - MANTIS_CONFIG_FROM_EMAIL='<your email>'
      - MANTIS_CONFIG_SMTP_HOST='smtp-relay.gmail.com'
      - MANTIS_CONFIG_SMTP_PORT=587
      - MANTIS_CONFIG_SMTP_PASSWORD='<your password>'
      - MANTIS_CONFIG_SMTP_USERNAME='<your username>'
      - MANTIS_CONFIG_SMTP_CONNECTION_MODE='tls'
      - MANTIS_WORKFLOW_JSON={"10":{"name":"new","traduction_name":"Nouveau","workflowName":"NEW_","color":"#fcbdbd","level":"10","to":["20","30","40","50","60","65","70","75","80","85","90"],"bug_button":"Nouveau bogue","bug_title":"Nouveau bogue","email_notification":"Le bogue suivant est maintenant au statut « nouveau » (encore)","my_view_title":""},"20":{"name":"feedback","traduction_name":"Retour d'information","color":"#e3b7eb","level":"20","to":["30","40","50","60","65","70","75","80","85","90"],"bug_button":"DemDetande de retour d'information","bug_title":"Demander des informations sur le bogue","email_notification":"Le bogue suivant nécessite votre commentaire.","my_view_title":"En attente de suivi de moi"},"30":{"name":"acknowledged","traduction_name":"Accepté","color":"#ffcd85","level":"30","to":["20","40","50","60","65","70","75","80","85","90"],"bug_button":"Accepter le bogue","bug_title":"Accepter le bogue","email_notification":"Le bogue suivant a été accepté.","my_view_title":""},"40":{"name":"confirmed","traduction_name":"Confirmé","color":"#fff494","level":"40","to":["20","50","60","65","70","75","80","85","90"],"bug_button":"Confirmer le bogue","bug_title":"Confirmer le bogue","email_notification":"Le bogue suivant a été confirmé.","my_view_title":""},"50":{"name":"assigned","traduction_name":"Affecté","color":"#c2dfff","level":"50","to":["20","60","65","70","75","80","85","90"],"bug_button":"Assigner le bogue","bug_title":"Assigner le bogue","email_notification":"Le bogue suivant a été assigné.","my_view_title":""},"60":{"name":"deployed_dev","traduction_name":"Livré {DEV}","color":"#8efa24","level":"60","to":["20","50","70","65","70","75","80","85","90"],"bug_button":"Livrer en dev","bug_title":"Livraison en dev","email_notification":"Le bogue suivant à été livré en dev","my_view_title":"Livré en dev"},"65":{"name":"deployed_qual","traduction_name":"Livré {QUAL}","color":"#05a395","level":"65","to":["20","50","75","80","85","90"],"bug_button":"Livrer en qual","bug_title":"Livraison en qual","email_notification":"Le bogue suivant à été livré en qual","my_view_title":"Livré en qual"},"70":{"name":"recipe_ok","traduction_name":"Recette OK","color":"#27f531","level":"70","to":["50","80","85","90"],"bug_button":"Recette OK","bug_title":"Recette OK","email_notification":"La recette du bogue suivant est validée (OK)","my_view_title":"Recette OK"},"75":{"name":"recipe_ko","traduction_name":"Recette KO","color":"#dd1919","level":"75","to":["20","50","75","90"],"bug_button":"Recette KO","bug_title":"Recette KO","email_notification":"La recette du bogue suivant a échouée (KO)","my_view_title":"Recette KO"},"80":{"name":"deployed_prod","traduction_name":"Livré {PROD}","color":"#9239ec","level":"85","to":["20","50","80","90"],"bug_button":"Livrer en prod","bug_title":"Livraison en prod","email_notification":"Le bogue suivant à été livré en prod","my_view_title":"Livré en prod"},"85":{"name":"resolved","traduction_name":"Résolu","color":"#d2f5b0","level":"60","to":["50","65","70","90"],"bug_button":"Traiter le bogue","bug_title":"Traitement d'un bogue","email_notification":"Le bogue suivant a été résolu.","my_view_title":"Résolu"},"90":{"name":"closed","traduction_name":"Fermé","color":"#c9ccc4","level":"90","to":["50","20"],"bug_button":"Fermer un bogue","bug_title":"Fermer un bogue","email_notification":"Le bogue suivant a été fermé.","my_view_title":"Fermé"}}

    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    volumes:
    - mantis-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mantis
      MYSQL_DATABASE: mantis
