#!/bin/bash
set -eo pipefail

echo '<?php ' > /var/www/html/config/config_inc.php
while read -r VAL ; do
    if [[ $VAL =~ ^MANTIS_CONFIG_* ]]; then
        VARNAME=`echo "$VAL" | sed -r 's/^([^=]*)=(.*)$/\1/'`
        VARVALUE=`echo "$VAL" | sed -r 's/^([^=]*)=(.*)$/\2/'`
        PHPVARNAME=`echo "$VARNAME" | sed 's/MANTIS_CONFIG_/\$g_/g' | tr '[:upper:]' '[:lower:]'`
        echo -e "$PHPVARNAME=$VARVALUE;" >> /var/www/html/config/config_inc.php
    fi
done < <(env)

sed -i 's/g_phpmailer_method/g_phpMailer_method/g' /var/www/html/config/config_inc.php

test -d admin && chmod -rx admin && mv admin .admin
if [ ! -z "$MANTIS_ENABLE_ADMIN" ]; then
  test -d .admin && mv .admin admin && chmod +rx admin
fi

apache2-foreground
